server:
  port: ${PORT:8081}

spring:
  application:
    name: user-management-service
  profiles:
    active: ${ACTIVE_PROFILE:oauth2} #oauth2, basic-auth, apikey, mTLS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_GENERATE_STATISTICS:false}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_management_service
    username: user_management_service_admin
    password: user_management_service_admin

token:
    expiry:
      days: 1

logging:
  level:
    org:
      springframework:
        security: trace

eureka:
    client:
      service-url:
        defaultZone: "http://localhost:8088/eureka/"
